version: '3.0'

services:
  protractor:
    image: "caltha/protractor:latest"
    networks:
    - demo_overlay_net
    depends_on:
    - selenium-hub
    environment:
      MANUAL: 'yes'
    volumes:
    - /Users/garystafford/Documents/projects/voter-services/voter-client:/project

  selenium-hub:
    image: "selenium/hub:latest"
    networks:
    - demo_overlay_net
    ports:
    - 4444:4444/tcp

  node-chrome:
    image: "selenium/node-chrome-debug:latest"
    networks:
    - demo_overlay_net
    depends_on:
    - selenium-hub
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444
    ports:
    - 5900:5900/tcp

  node-firefox:
    image: "selenium/node-firefox-debug:latest"
    networks:
    - demo_overlay_net
    depends_on:
    - selenium-hub
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444
    ports:
    - 5901:5900/tcp

networks:
  demo_overlay_net:

volumes:
  demo_data_vol:
