# Selenium Stack with Protractor (manual test mode)

version: '3.0'

services:
  protractor:
    image: "caltha/protractor:latest"
    depends_on:
    - selenium-hub
    environment:
      MANUAL: 'yes'
    volumes:
    - ${PROJECT_PATH}:/project
    networks:
    - demo_overlay_net

  selenium-hub:
    image: "selenium/hub:latest"
    ports:
    - 4444:4444/tcp
    networks:
    - demo_overlay_net

  node-chrome:
    image: "selenium/node-chrome-debug:latest"
    depends_on:
    - selenium-hub
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444
    ports:
    - 5900:5900/tcp
    networks:
    - demo_overlay_net

  node-firefox:
    image: "selenium/node-firefox-debug:latest"
    depends_on:
    - selenium-hub
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444
    ports:
    - 5901:5900/tcp
    networks:
    - demo_overlay_net

networks:
  demo_overlay_net:

volumes:
  demo_data_vol:
